# SPDX-License-Identifier: GPL-2.0-only
# borrowed from Makefile for user memory selftests

# No binaries, but make sure arg-less "make" doesn't trigger "run_tests"
all:

# or maybe just let it run_tests, with narrow test-progs ??
TEST_PROGS := dyndbg_selftest.sh

include ../lib.mk
